stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:20.10.16
  services:
     - docker:20.10.16-dind
  before_script:
    - docker login -u $USER -p $PASSWORD registry.gitlab.com 
  script:
    -docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    -docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
