stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy

Installing_gitlabRunner:
  stage: installation
  image : ubuntu:latest
  before_script:
    - apt update && apt install sshpass -y
    
    - sshpass -p"$password" ssh debian@51.210.179.152 -y 
  script: 
    - sudo apt-get install -y curl openssh-server ca-certificates perl
    - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash export GITLAB_RUNNER_DISABLE_SKEL=true; sudo -E apt-get install gitlab-runner







  #under construction
Linting_Dockerfile:
  stage: optimize
  image: docker:20
  script:
    - sed -i 's/FROM node:/FROM node:alpine/' Dockerfile
    - hadolint Dockerfile || true 
  artifacts:
    paths:
      - Dockerfile
  #under construction

 

# to scan if any sensitive data has been pushed to git
gitguardian scan:
  stage: scanning
  image: gitguardian/ggshield:latest
  script: ggshield secret scan ci
# execute the provided application test 
test-job:   
  stage: test 
  image: node:14
  before_script:
    - apt update
    - apt-get install mariadb-server -y
    - /etc/init.d/mysql start
    - mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
    - npm install -g sequelize-cli 
    - npm install
    - mysql -u root -proot -e "CREATE DATABASE student_test;"
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install -g nyc 
  script:
    - nyc mocha --exit

