stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:20
  services:
     - name: docker:20-dind
       entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
       alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    
 
   
  before_script:
    -  apt-get install mariadb-server -y
    - /etc/init.d/mysql start
    - mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
    - mysql -u root -proot -e "CREATE DATABASE student_dev;"
    - docker login -u $USER -p $PASSWORD registry.gitlab.com

  script:
    - docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws .
    - docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws 
  
