stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:23
  services:
     - docker:23-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - DOCKER_HOST=tcp://40.80.95.202:2375 docker login -u $USER -p $PASSWORD registry.gitlab.com

  script:
    - DOCKER_HOST=tcp://172.17.0.1:2375 docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    - DOCKER_HOST=tcp://172.17.0.1:2375 docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
