stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:stable
  services:
     - docker:stable-dind
  before_script:
    - docker login  registry.gitlab.com 
  script:
    -docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    -docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
