stages:   
  - install
  - optimize
  - scanning  
  - test
  - build
  - deploy


Installing_gitlabRunner:
  stage: install
  image : ubuntu:18.04
  script:
    - apt-get update
    - apt-get install sshpass -y
    - sshpass -p 'fGKP7ACuRTH9' ssh debian@51.210.179.152

