stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-job:   
  stage: test 
  image: mysql:8.0.32
  before_script:
    - apt-get update 
    - sudo apt-get install nodejs
    - sudo apt-get install npm  
    - npm install -g sequelize-cli 
    - npm install
    - mysql -u root -p -e "CREATE DATABASE student_test;"
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install --save-dev nyc 
  script:
    - nyc mocha --exit

lint-test-job:  
  stage: test   
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
