stages:          
  - build
  - test
  - deploy



test-job:   
  stage: test 
  image: node:14
 

  before_script:
    - apt update
    
    - apt-get install mariadb-server -y
    - /etc/init.d/mysql start
    - mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
    - mysql -u root -p 'root' -e "CREATE DATABASE student_test;"
    - npm install -g sequelize-cli 
    - npm install
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install --save-dev nyc 
  script:
    - nyc mocha --exit

