stages:          
  - build
  - test
  - deploy



test-job:   
  stage: test 
  image: node:19-alpine3.16
  before_script:
    
    - apk add --no-cache mysql-client
    - apk add --no-cache mariadb mariadb-client
    - rc-service mysql start
    - mysql -u root -p -e "CREATE DATABASE student_test;"
    - npm install -g sequelize-cli 
    - npm install
   
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install --save-dev nyc 
  script:
    - nyc mocha --exit

