stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:23
  services:
     - docker:docker:19.03-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $USER -p $PASSWORD registry.gitlab.com

  script:
    - docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    - docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
