stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: 20.10.16:stable
  services:
     - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - DOCKER_HOST=tcp://40.80.95.202:2375 docker login -u $USER -p $PASSWORD registry.gitlab.com

  script:
    -docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    -docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
