stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:20
  services:
     - name: docker:20-dind
       entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
       alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
 
  
  before_script:
    - docker login -u $USER -p $PASSWORD registry.gitlab.com

  script:
    - docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws .
    - docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
