stages:   
  - installation
  - optimize
  - scanning  
  - test
  - build
  - deploy


Building:
  stage: build
  image: docker:stable
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
     - docker:stable-dind
  before_script:
    - docker login -u $USER -p $PASSWORD registry.gitlab.com --host=40.80.95.202:2375
  script:
    -docker build -t registry.gitlab.com/first617/accelerating-devsecops-on-aws:latest .
    -docker push registry.gitlab.com/first617/accelerating-devsecops-on-aws
  
