stages:          
  - build
  - test
  - deploy



test-job:   
  stage: test 
  image: node:14
  before_script:
    -  apt update
    -  apt install mysql-server-8.0 -y 
    -  systemctl start mysql
    - mysql -u root -p -e "CREATE DATABASE student_test;"
    - npm install -g sequelize-cli 
    - npm install
   
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install --save-dev nyc 
  script:
    - nyc mocha --exit

