stages:   
  - verify
  - optimize
  - scanning  
  - test
  - build
  - deploy

Linting_Dockerfile:
  stage: verify
  image: registry.gitlab.com/pipeline-components/hadolint:latest
  script:
    - sed -i 's/FROM node:/FROM node:alpine/' Dockerfile
    - cat Dockerfile
    - hadolint Dockerfile || true 
    
gitguardian scan:
  image: gitguardian/ggshield:latest
  stage: scanning
  script: ggshield secret scan ci
  
test-job:   
  stage: test 
  image: node:14
  before_script:
    - apt update
    - apt-get install mariadb-server -y
    - /etc/init.d/mysql start
    - mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
    - npm install -g sequelize-cli 
    - npm install
    - mysql -u root -proot -e "CREATE DATABASE student_test;"
    - sequelize db:migrate --env=test
    - npm install -g mocha 
    - npm install -g nyc 
  script:
    - nyc mocha --exit

